
services:
  db:
    container_name: postgres_database
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_USER: evidence
      POSTGRES_PASSWORD: evidence
      POSTGRES_DB: evidence
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: postgres_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db



volumes:
  postgres_data:
    driver: local
